COMP: Fix build error using "vnl_math::isnan" instead of legacy "vnl_math_isnan"
This commit fixes errors like the following:

  /path/to/SPHARM-PDM/Libraries/Shape/Algorithms/BinaryMask3DEqualAreaParametricMeshSource.txx:330:25: error: ‘vnl_math_isnan’ was not declared in this scope
         if( vnl_math_isnan(curVertex[0]) || vnl_math_isnan(curVertex[1]) || vnl_math_isnan(curVertex[2]) )
                           ^