COMP: Fix linking of GenParaMeshCLPTest against ITK with custom namespace
This commit fixes regressions introduced in Slicer/Slicer@8f67453b0 (ENH: Add
support for importing "itk" from python wheels installed from PyPI).

It addresses link errors like the following by adding missing includes:

  CMakeFiles/GenParaMeshCLPTest.dir/vtkTest.cxx.o:vtkTest.cxx:
  itk::(anonymous namespace)::TransformIOFactoryRegisterRegisterList:
  error: undefined reference to 'itk::HDF5TransformIOFactoryRegister__Private()'